In [13]:
!pip install -q lion-pytorch comet_ml

In [14]:
import torch
import numpy as np
import matplotlib.pyplot as plt
from torchvision import datasets, transforms
import torch.nn.functional as F
import torchvision.transforms as T

from PIL import Image
import json
from math import prod
from huggingface_hub import hf_hub_download
import tqdm
transform_t_to_pil = T.ToPILImage()
transform_to_t = transforms.Compose([transforms.ToTensor()])
import utils
from utils import get_all_bounding_boxes, segment, calculate_initial_theta, stack_alpha_aware, AestheticPredictor, get_random_initial_position
# from lion_pytorch import Lion
from datetime import datetime
import random
from huggingface_hub import hf_hub_download
import timm
from lion_pytorch import Lion
import torch.nn as nn
import comet_ml

In [3]:
# Transformations
resnet_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

In [4]:
device = "cpu"

In [5]:
# Load pre-trained ResNet model
random_predictor = timm.create_model('resnet50', pretrained=True)
random_predictor.fc = nn.Linear(random_predictor.fc.in_features, 2)  # Modify the classifier to output 2 classes
random_predictor.to(device)

local_filename = hf_hub_download(repo_id="mowoe/random-layout-classifier", filename="random-layout-classifier.pt")
random_predictor.load_state_dict(torch.load(local_filename, map_location="cpu"))

<All keys matched successfully>

In [6]:
im = Image.open('../combined/5373.jpg')
im = im.convert('RGBA')
im = im.resize((1440, 2560), Image.Resampling.LANCZOS)


with open('../combined/5373.json', "r") as f:
    image_json = json.load(f)

reduced_segments = [s for s in segment(im,image_json) if (prod(s[0].size) < 0.80*prod(im.size)) and (prod(s[0].size)>1)]

In [7]:
im.size

(1440, 2560)

In [8]:
def get_all_bounding_boxes(item):
    all_boxes = []
    if "bounds" in item.keys() and "resource-id" in item.keys():
        all_boxes.append((item["bounds"],item["resource-id"]))
    if "children" in item.keys():
        for child in item["children"]:
            for box in get_all_bounding_boxes(child):
                all_boxes.append(box)
    return all_boxes

In [9]:
class MultiSegmentUIOptimizerWithBackgroundParam(torch.nn.Module):
    def __init__(self,segments_and_positions: list, original_image_size: tuple):
        super().__init__()
        self.original_image_size = original_image_size
        self.segments_and_positions = segments_and_positions
        self.canvas_size = (1,3,original_image_size[1],original_image_size[0])
        print(f"Canvas size is {self.canvas_size}")

        initial_vector = []
        for segment,position in segments_and_positions:
            # initial_theta = calculate_initial_theta(segment,original_image_size,position)
            initial_theta = get_random_initial_position(segment,original_image_size,position)
            initial_vector.append([initial_theta[0][2],initial_theta[1][2]])

        self.coordinates = torch.nn.Parameter(torch.tensor(initial_vector))
        print(self.coordinates)
        self.background_color = torch.nn.Parameter(torch.tensor(np.array([1.0,1.0,1.0]),dtype=torch.float))
        

    def forward(self):
        segments_on_canvas = []

        # Create background image from parameter
        bg_col = torch.clamp(self.background_color, min=0, max=1)
        #print(f"Clamped bg to {bg_col}")
        red = torch.tile(bg_col[0],self.original_image_size[::-1])
        green = torch.tile(bg_col[1],self.original_image_size[::-1])
        blue = torch.tile(bg_col[2],self.original_image_size[::-1])
        alpha = torch.tile(torch.tensor(1.0),self.original_image_size[::-1])
        background = torch.stack([red,green,blue,alpha]).unsqueeze(0)
        #print(background.detach().sum())
        #background = torch.tile(self.background_color,self.original_image_size)
        
        segments_on_canvas.append(background)
        
        for n in range(len(self.segments_and_positions)):
            # We need to calculate the proper ratios, to artificially warp the segment on to a bigger canvas without distorting it (see notebook 01)
            x_ratio = self.original_image_size[0] / self.segments_and_positions[n][0].size[0]
            y_ratio = self.original_image_size[1] / self.segments_and_positions[n][0].size[1]
            
            # Affine matrix
            theta = [
                [x_ratio, 0.0    , 0.0],
                [0.0    , y_ratio, 0.0]
            ]
            theta_tensor = torch.as_tensor(theta)[None]

            theta_tensor[0][0][2]+=self.coordinates[n][0]
            theta_tensor[0][1][2]+=self.coordinates[n][1]
            
            # Generate flow field
            grid = F.affine_grid(theta_tensor, self.canvas_size).type(torch.FloatTensor)
            x = F.grid_sample(transform_to_t(self.segments_and_positions[n][0]).unsqueeze(0), grid)
            segments_on_canvas.append(x)



        return segments_on_canvas

In [15]:
appsthetics_predictor = torch.load("../Dataset_estetica/Regressao/model123")

In [11]:
learning_rates = [0.1,0.05,0.01,0.005,0.001,0.0005]
optimisers = [Lion,torch.optim.AdamW]

In [22]:
random_classifier_criterion = nn.CrossEntropyLoss()
# random_classifier_loss_weight = 0.33
random_classifier_loss_weight = 1.0
random_classifier_target = torch.Tensor([1.0]).to(torch.long)

In [ ]:
for lr in learning_rates:
    for optimiser in optimisers:
        experiment = comet_ml.Experiment(
            api_key="<revoked>",
            project_name="mowoe/bachelor-thesis-hyperparam-sweep"
        )

        experiment.log_parameters({
            "optim":str(optimiser),
            "lr":lr
        })

        reduced_losses = []

        # Try for 3 different seeds: 
        for y in range(3):
            msUIo_wbg = MultiSegmentUIOptimizerWithBackgroundParam(reduced_segments, im.size)
            
            
            optim = optimiser(msUIo_wbg.parameters(),lr=lr)
            initial_loss = None
    
            
            
            for x in tqdm.tqdm(range(25)):
                optim.zero_grad()
    
                canvasses = msUIo_wbg()
        
                generated_image = stack_alpha_aware(canvasses)
                # Remove Alpha channel
                generated_image = generated_image[:3]
            
                score = appsthetics_predictor["model"](generated_image.unsqueeze(0))
            
                random_classifier_logits = random_predictor(resnet_transform(generated_image.unsqueeze(0)))
                random_loss = random_classifier_criterion(random_classifier_logits,random_classifier_target)
            
                combined_loss = random_classifier_loss_weight * random_loss + (1-random_classifier_loss_weight) * ((1-score)*10)
                    
                loss = -score
                loss.backward()
                optim.step()
    
                if not initial_loss:
                    initial_loss = combined_loss.item()
               
            
                # Save image as png to create gif
                pil_image = transform_t_to_pil(generated_image.detach())
                pil_image = pil_image.resize((int(pil_image.size[0]/4),int(pil_image.size[1]/4)), Image.Resampling.LANCZOS)
                experiment.log_image(pil_image,step=(x+10*y))
                experiment.log_metric("loss", combined_loss.item(), step=(x+10*y))
        
        reduced_losses.append((1-(combined_loss.item()/initial_loss))**2)

        

        experiment.log_metric("avg_squared_loss_perc_reduction",sum(reduced_losses)/len(reduced_losses))
        
        experiment.end()

COMET WARNING: To get all data logged automatically, import comet_ml before the following modules: torch.
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : dull_barbel_5024
COMET INFO:     url                   : https://www.comet.com/mowoe/mowoe-bachelor-thesis-hyperparam-sweep/ab83a8b13e7145d48c2a583aa1ca46e7
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     loss [24] : (7.164503574371338, 10.778894424438477)
COMET INFO:   Parameters:
COMET INFO:     lr    : 0.1
COMET INFO:     optim : <class 'torch.optim.adamw.AdamW'>
COMET INFO:   Uploads:
COMET INFO:     conda-environment-definition : 1
COMET INFO:     conda-info                   : 1
COMET INFO:     conda-specification          : 1
COM

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[ -1.9200, -10.6559],
        [ -0.3738,  -6.4977],
        [  0.3894,  -0.8312],
        [  0.0752,  19.9029],
        [  2.6668,   2.4214],
        [  0.0000, -12.8590],
        [  0.0000,   5.7405]], dtype=torch.float64, requires_grad=True)


  0%|          | 0/25 [00:00<?, ?it/s]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4343: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
  4%|▍         | 1/25 [00:14<05:44, 14.37s/it]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warning

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[  5.1258,  -4.2257],
        [  0.4999, -10.3483],
        [  0.1464,  -7.7551],
        [ -1.9631, -24.7587],
        [  3.1382,  -2.9370],
        [  0.0000,   7.3928],
        [  0.0000,  19.6109]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [05:50<00:00, 14.02s/it]


Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[  7.3807,   0.6018],
        [ -0.2767,  12.8989],
        [ -0.1824,  -6.8801],
        [ -0.9662,  15.5711],
        [ -2.2737,  13.9255],
        [  0.0000,  -2.1150],
        [  0.0000, -11.6126]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [05:51<00:00, 14.05s/it]
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : subsequent_condensation_3117
COMET INFO:     url                   : https://www.comet.com/mowoe/mowoe-bachelor-thesis-hyperparam-sweep/d22502b3a28e4f48bc48d2bba23604fd
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     avg_squared_loss_perc_reduction : 0.02653656607931545
COMET INFO:     loss [75]                       : (4.5235700607299805, 8.388734817504883)
COMET INFO:   Parameters:
COMET INFO:     lr    : 0.1
COMET INFO:     optim : <class 'lion_pytorch.lion_pytorch.Lion'>
COMET INFO:   Uploads:
COMET INFO:     conda-environment-definition : 1
COMET INFO:     conda-info                   : 1

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[-3.8863e+00, -1.2712e+01],
        [-3.0130e-02,  1.5823e+01],
        [-1.7263e-01, -8.8114e+00],
        [ 3.7270e-01,  3.0682e+01],
        [-2.1883e+00,  1.3665e+01],
        [ 0.0000e+00,  4.0493e+00],
        [ 0.0000e+00, -1.6553e+01]], dtype=torch.float64, requires_grad=True)


  0%|          | 0/25 [00:00<?, ?it/s]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4343: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
  4%|▍         | 1/25 [00:20<08:04, 20.20s/it]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warning

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[-5.5710,  8.2353],
        [ 0.2101, -7.1582],
        [ 0.3538, -3.6254],
        [ 1.3313,  9.8730],
        [ 2.5471, 12.3409],
        [ 0.0000, 10.7658],
        [ 0.0000, 10.0919]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [05:45<00:00, 13.82s/it]


Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[ -1.6513,   7.7629],
        [  0.5305,   7.3120],
        [  0.4123,  -2.2081],
        [  2.1388,  15.1154],
        [ -2.0870, -10.2097],
        [  0.0000,   4.8159],
        [  0.0000, -12.6342]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [05:46<00:00, 13.86s/it]
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : specific_contingency_1173
COMET INFO:     url                   : https://www.comet.com/mowoe/mowoe-bachelor-thesis-hyperparam-sweep/33a01f25af82454c96c76176371bdbab
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     avg_squared_loss_perc_reduction : 0.019868514117024377
COMET INFO:     loss [75]                       : (4.956974029541016, 8.314827919006348)
COMET INFO:   Parameters:
COMET INFO:     lr    : 0.1
COMET INFO:     optim : <class 'torch.optim.adamw.AdamW'>
COMET INFO:   Uploads:
COMET INFO:     conda-environment-definition : 1
COMET INFO:     conda-info                   : 1
COMET INF

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[-6.3033e+00,  1.8424e+00],
        [ 2.1271e-02, -1.8643e+00],
        [ 3.0469e-01, -2.3501e+00],
        [ 1.5324e+00, -1.9477e+01],
        [-3.2920e+00,  2.5439e+00],
        [ 0.0000e+00,  5.5743e+00],
        [ 0.0000e+00,  2.5333e+01]], dtype=torch.float64, requires_grad=True)


  0%|          | 0/25 [00:00<?, ?it/s]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4343: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
  4%|▍         | 1/25 [00:10<04:23, 10.99s/it]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warning

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[  3.8015,  13.7914],
        [  0.0266, -13.2885],
        [ -0.1661,   1.6503],
        [ -1.7097, -11.8702],
        [ -1.1730,  -8.2560],
        [  0.0000,   5.4275],
        [  0.0000,   2.0428]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [03:41<00:00,  8.84s/it]


Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[  1.6808,  -7.6708],
        [  0.6227,  -0.9545],
        [ -0.3863,   0.1777],
        [ -1.1773, -30.3914],
        [ -0.1291,   6.6848],
        [  0.0000,   4.3126],
        [  0.0000,  19.5729]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [03:35<00:00,  8.61s/it]
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : supreme_soursop_1678
COMET INFO:     url                   : https://www.comet.com/mowoe/mowoe-bachelor-thesis-hyperparam-sweep/08d3f3d05b334f4c9ad30b4e10858ca4
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     avg_squared_loss_perc_reduction : 0.012370783668881925
COMET INFO:     loss [75]                       : (5.21538782119751, 8.080414772033691)
COMET INFO:   Parameters:
COMET INFO:     lr    : 0.05
COMET INFO:     optim : <class 'lion_pytorch.lion_pytorch.Lion'>
COMET INFO:   Uploads:
COMET INFO:     conda-environment-definition : 1
COMET INFO:     conda-info                   : 1
COMET I

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[  3.5740,  -6.0224],
        [  0.4905,  15.7476],
        [  0.0372,  -5.4227],
        [ -1.2571,  22.3680],
        [ -0.6932,  -1.7390],
        [  0.0000,   9.6173],
        [  0.0000, -10.1807]], dtype=torch.float64, requires_grad=True)


  0%|          | 0/25 [00:00<?, ?it/s]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4343: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
  4%|▍         | 1/25 [00:09<03:39,  9.15s/it]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warning

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[  6.3796,  -9.6418],
        [  0.6112,  -1.7515],
        [  0.3375,  -2.5703],
        [  0.2918, -19.8632],
        [ -2.9511,   0.5159],
        [  0.0000,  -9.9322],
        [  0.0000,  -1.1254]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [03:37<00:00,  8.70s/it]


Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[ -1.5942,   7.2059],
        [  0.4876,  15.2687],
        [ -0.4586,   2.2810],
        [ -1.5184, -25.7477],
        [  2.6561,  -7.7848],
        [  0.0000,  -9.3489],
        [  0.0000, -19.3297]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [03:33<00:00,  8.56s/it]
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : preliminary_shares_1893
COMET INFO:     url                   : https://www.comet.com/mowoe/mowoe-bachelor-thesis-hyperparam-sweep/649dbdbecaf84f7c8144c6c48c583d94
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     avg_squared_loss_perc_reduction : 0.020282572359471895
COMET INFO:     loss [75]                       : (5.771804332733154, 8.638378143310547)
COMET INFO:   Parameters:
COMET INFO:     lr    : 0.05
COMET INFO:     optim : <class 'torch.optim.adamw.AdamW'>
COMET INFO:   Uploads:
COMET INFO:     conda-environment-definition : 1
COMET INFO:     conda-info                   : 1
COMET INFO

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[ 5.3629,  0.9082],
        [-0.5373, -5.7903],
        [-0.6015,  8.9004],
        [-2.2273, 24.1976],
        [-1.0252, -2.1026],
        [ 0.0000, -2.3874],
        [ 0.0000, 26.7102]], dtype=torch.float64, requires_grad=True)


  0%|          | 0/25 [00:00<?, ?it/s]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4343: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
  4%|▍         | 1/25 [00:08<03:24,  8.51s/it]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warning

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[  1.7368,  -2.2213],
        [ -0.2594,  11.0371],
        [  0.5761,  -0.4928],
        [  0.9986, -22.9870],
        [  1.8665,   4.4923],
        [  0.0000,  10.1170],
        [  0.0000,  -9.8272]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [03:35<00:00,  8.63s/it]


Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[  0.3643,   8.6322],
        [ -0.3408, -12.9930],
        [  0.5555,   3.5024],
        [ -0.9564,  -2.0698],
        [ -0.4257,  11.7940],
        [  0.0000,  -3.2915],
        [  0.0000,  20.5152]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [03:44<00:00,  8.97s/it]
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : striking_duck_741
COMET INFO:     url                   : https://www.comet.com/mowoe/mowoe-bachelor-thesis-hyperparam-sweep/9a13b20cfcdd40e7960069632fd7c86f
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     avg_squared_loss_perc_reduction : 8.280987018838045e-05
COMET INFO:     loss [75]                       : (5.662373065948486, 8.199675559997559)
COMET INFO:   Parameters:
COMET INFO:     lr    : 0.01
COMET INFO:     optim : <class 'lion_pytorch.lion_pytorch.Lion'>
COMET INFO:   Uploads:
COMET INFO:     conda-environment-definition : 1
COMET INFO:     conda-info                   : 1
COMET IN

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[ 3.4214, -6.5909],
        [-0.4764, -4.5336],
        [ 0.6165,  8.5807],
        [-0.7619,  2.3999],
        [-2.1813,  4.7779],
        [ 0.0000,  1.0948],
        [ 0.0000,  1.3665]], dtype=torch.float64, requires_grad=True)


  0%|          | 0/25 [00:00<?, ?it/s]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4343: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
  4%|▍         | 1/25 [00:08<03:32,  8.84s/it]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warning

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[ 2.0752e+00, -1.0070e+01],
        [-1.6218e-01, -2.4642e+00],
        [-1.4509e-02,  3.1232e+00],
        [-7.8295e-01,  2.7127e+01],
        [-2.2087e+00, -6.2053e+00],
        [ 0.0000e+00,  1.1495e+01],
        [ 0.0000e+00, -2.6228e+01]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [03:41<00:00,  8.87s/it]


Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[  5.8157,   3.6902],
        [ -0.6566, -10.5444],
        [ -0.4624,   3.1911],
        [ -1.2307,  -2.9143],
        [ -0.8856,   6.7907],
        [  0.0000,  -0.6555],
        [  0.0000,  -0.1523]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [03:35<00:00,  8.63s/it]
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : late_newt_2403
COMET INFO:     url                   : https://www.comet.com/mowoe/mowoe-bachelor-thesis-hyperparam-sweep/825b324da2534774b3e4e4d662908e07
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     avg_squared_loss_perc_reduction : 0.0007548738440155407
COMET INFO:     loss [75]                       : (6.186100006103516, 8.422450065612793)
COMET INFO:   Parameters:
COMET INFO:     lr    : 0.01
COMET INFO:     optim : <class 'torch.optim.adamw.AdamW'>
COMET INFO:   Uploads:
COMET INFO:     conda-environment-definition : 1
COMET INFO:     conda-info                   : 1
COMET INFO:     co

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[ 5.0802,  5.7965],
        [ 0.3555, -0.1275],
        [-0.0836,  3.4538],
        [ 2.1628,  4.0384],
        [ 3.2323, 13.3663],
        [ 0.0000,  0.0657],
        [ 0.0000,  7.4252]], dtype=torch.float64, requires_grad=True)


  0%|          | 0/25 [00:00<?, ?it/s]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4343: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
  4%|▍         | 1/25 [00:09<03:41,  9.25s/it]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warning

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[-6.2290e+00,  5.7975e+00],
        [ 2.8213e-01, -1.0945e-02],
        [ 5.1610e-01, -1.8575e+00],
        [ 1.7067e+00, -7.6813e+00],
        [ 2.6542e+00,  2.0002e+00],
        [ 0.0000e+00, -1.2557e+01],
        [ 0.0000e+00, -2.6819e+01]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [03:43<00:00,  8.94s/it]


Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[ -2.6803,  10.4620],
        [ -0.1912, -10.2657],
        [ -0.3488,   2.4355],
        [ -0.5887,  12.7377],
        [  2.9432, -10.2772],
        [  0.0000,  -9.0433],
        [  0.0000,  23.9841]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [03:40<00:00,  8.80s/it]
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : absent_jambul_2095
COMET INFO:     url                   : https://www.comet.com/mowoe/mowoe-bachelor-thesis-hyperparam-sweep/7e76b248a71943698211f40e75163571
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     avg_squared_loss_perc_reduction : 1.3149506060140952e-05
COMET INFO:     loss [75]                       : (4.831896781921387, 7.655590534210205)
COMET INFO:   Parameters:
COMET INFO:     lr    : 0.005
COMET INFO:     optim : <class 'lion_pytorch.lion_pytorch.Lion'>
COMET INFO:   Uploads:
COMET INFO:     conda-environment-definition : 1
COMET INFO:     conda-info                   : 1
COMET

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[-3.4307, -7.6104],
        [ 0.3470, 13.4128],
        [ 0.6003, -7.3690],
        [-0.1920, 26.5586],
        [ 1.7937, 11.8133],
        [ 0.0000, 12.0680],
        [ 0.0000,  5.9325]], dtype=torch.float64, requires_grad=True)


  0%|          | 0/25 [00:00<?, ?it/s]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4343: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
  4%|▍         | 1/25 [00:08<03:26,  8.60s/it]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warning

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[ -2.5334,  -7.4601],
        [  0.0593,   7.0878],
        [ -0.4865,   1.4278],
        [  2.1619, -21.5301],
        [ -1.9550,   5.3097],
        [  0.0000,  12.7777],
        [  0.0000, -26.5986]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [03:47<00:00,  9.09s/it]


Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[  4.8931,   0.2500],
        [ -0.6618, -12.7307],
        [ -0.4186,   7.0656],
        [  0.1232,  -4.4600],
        [ -1.7523,  11.7416],
        [  0.0000,   5.1870],
        [  0.0000,  -8.2909]], dtype=torch.float64, requires_grad=True)


100%|██████████| 25/25 [03:47<00:00,  9.10s/it]
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------------------------------------------------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     name                  : different_tick_8668
COMET INFO:     url                   : https://www.comet.com/mowoe/mowoe-bachelor-thesis-hyperparam-sweep/3c084967d7014c0cab4582e79d8b3466
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     avg_squared_loss_perc_reduction : 0.013393714434265309
COMET INFO:     loss [75]                       : (5.4227519035339355, 8.103497505187988)
COMET INFO:   Parameters:
COMET INFO:     lr    : 0.005
COMET INFO:     optim : <class 'torch.optim.adamw.AdamW'>
COMET INFO:   Uploads:
COMET INFO:     conda-environment-definition : 1
COMET INFO:     conda-info                   : 1
COMET INFO: 

Canvas size is (1, 3, 2560, 1440)
Parameter containing:
tensor([[  1.8563,  -5.8283],
        [  0.6481,   0.7591],
        [  0.5925,   7.2506],
        [  1.6428, -25.5575],
        [ -1.0654,  -5.5741],
        [  0.0000,   1.1248],
        [  0.0000, -20.5481]], dtype=torch.float64, requires_grad=True)


  0%|          | 0/25 [00:00<?, ?it/s]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4343: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
  4%|▍         | 1/25 [00:08<03:27,  8.63s/it]/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py:4404: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warning